title: Site


columns:
  # - width: 1/3
  #   sections:
  #     albums: sections/albums


 
  # - width: 1/2
  #   sections:
  #     notes: sections/wearable


  - width: 2/3
    sections:
      wearable:
        headline: Wearable
        extends: sections/wearable
      livable:
        headline: Livable
        extends: sections/livable
      audible:
        headline: Audible
        extends: sections/audible
      # notes:
      #   headline: Audible
      #   extends: sections/audible
      pages:
        type: pages
        create: default
        template:
          - home



